title: Steven Childs Projects
description: Blog and hosting space for personal work
baseurl: "/ScarletSage.github.io" # this is important for project pages
url: "https://schi-427.github.io"

theme: jekyll-theme-architect
markdown: kramdown

social_links:
  email: "mailto:schilds427@gmail.com"
  linkedin: "https://www.linkedin.com/in/steven-childs-10b7b086/"
